import React from 'react';
import { Link } from 'react-router-dom';
import { Bus, Compass, MapPin, ShieldCheck, Users, Utensils, BedDouble, Sunrise } from 'lucide-react';
import SEOJsonLd from '../components/SEOJsonLd';
import SharePlanPanel from '../components/SharePlanPanel';

const url='https://sage.healthandtravels.com/ru/arizona/grand-canyon-with-kids';
const es='https://sage.healthandtravels.com/es/arizona/gran-canon-con-ninos';
const faqs=[
{question:'Подходит ли Южный край Гранд-Каньона детям?',answer:'Да. Для первой поездки выбирайте Mather Point, короткий участок Rim Trail, Yavapai Geology Museum и регулярные перерывы. Маленьких детей постоянно держите рядом у края.'},
{question:'Нужно ли спускаться в каньон?',answer:'Нет. Семья может получить полноценное впечатление с края. Спуск под край значительно труднее обратного подъёма и требует отдельного плана.'},
{question:'Shuttle бесплатный?',answer:'Да, парковые shuttle бесплатны. Маршруты и расписание сезонные, поэтому проверяйте официальный сайт NPS в день поездки.'},
{question:'Где лучше остановиться?',answer:'Grand Canyon Village удобен для раннего старта, Tusayan находится у южного въезда, а Williams и Flagstaff подходят для более длинного road trip.'}
];
const plans=[
{title:'Первый визит без перегруза',for:'Маленькие дети или старшие родственники',text:'Visitor Center → Mather Point → ранний обед → Junior Ranger. Добавьте только одну необязательную остановку.'},
{title:'Прогулка вдоль края',for:'Дети школьного возраста',text:'Mather Point → подходящий участок Rim Trail → Yavapai Geology Museum → shuttle обратно.'},
{title:'Виды без лишней езды',for:'Смешанная группа',text:'Оставьте машину один раз, используйте shuttle и выбирайте остановки по энергии самого уставшего участника.'}
];
const stops=[
{title:'Mather Point',icon:Sunrise,text:'Самый простой первый большой вид рядом с Visitor Center. Приходите рано, чтобы уменьшить толпы и парковочный стресс.'},
{title:'Yavapai Point',icon:MapPin,text:'Панорама плюс музей геологии — полезная комбинация улицы и помещения.'},
{title:'Rim Trail',icon:Compass,text:'Выберите короткий развитый участок и развернитесь до усталости. Не все сегменты имеют ограждение.'},
{title:'Park shuttle',icon:Bus,text:'Бесплатный транспорт соединяет основные районы, но маршруты и часы работы меняются по сезону.'}
];
const safety=['Взрослый всегда находится между маленьким ребёнком и краем.','Не отходите назад ради фотографии и не бегайте у обрыва.','Проверьте погоду, дороги, молнии, снег и статус маршрутов до выезда.','Летом не планируйте напряжённый поход ниже края с 10:00 до 16:00.','Возьмите воду, перекусы, защиту от солнца и дополнительный слой одежды.'];
const shareText=['Гранд-Каньон с детьми — простой план:','1. Ранний приезд к Visitor Center','2. Mather Point','3. Короткий Rim Trail до Yavapai','4. Еда и Junior Ranger','5. Одна остановка на shuttle или отдых','','Правило: один вид, одна прогулка, один перерыв.',url].join('\n');
function alt(lang:string,href:string){let l=document.querySelector<HTMLLinkElement>(`link[rel="alternate"][hreflang="${lang}"]`);if(!l){l=document.createElement('link');l.rel='alternate';l.hreflang=lang;document.head.appendChild(l)}l.href=href}
export default function RussianGrandCanyonWithKids(){
React.useEffect(()=>{const old=document.documentElement.lang;document.documentElement.lang='ru';alt('ru',url);alt('es',es);alt('x-default',url);return()=>{document.documentElement.lang=old||'en'}},[]);
return <main className="min-h-screen bg-white text-zinc-950">
<SEOJsonLd title="Гранд-Каньон с детьми | Семейный план South Rim | Sage" description="Русский гид Sage по Южному краю Гранд-Каньона с детьми: виды, Rim Trail, shuttle, еда, жильё, безопасность и готовый маршрут." url={url} faqs={faqs} breadcrumbs={[{name:'Sage',url:'https://sage.healthandtravels.com/'},{name:'Аризона на русском',url:'https://sage.healthandtravels.com/ru'},{name:'Гранд-Каньон с детьми',url}]} />
<section className="bg-slate-950 px-6 py-20 text-white"><div className="mx-auto max-w-6xl"><div className="mb-6 flex gap-3 text-[11px] font-black uppercase tracking-[.2em]"><Link to="/ru" className="rounded-full border border-white/30 px-4 py-2">Русские гиды</Link><span className="rounded-full bg-teal-100 px-4 py-2 text-teal-950">South Rim</span></div><p className="text-[11px] font-black uppercase tracking-[.3em] text-teal-200">Большой вид · простой семейный день</p><h1 className="mt-4 max-w-4xl text-4xl font-black uppercase tracking-tight md:text-6xl">Гранд-Каньон с детьми</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-200">Выберите одну прогулку, используйте shuttle и оставьте силы на безопасное возвращение — без попытки увидеть весь каньон за один день.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/trip-builder?plan=ready&location=grand-canyon&kids=yes&group=family&activity=views&length=full-day&language=ru" className="rounded-full bg-blue-700 px-6 py-3 text-sm font-black uppercase">Составить план</Link><a href="https://www.nps.gov/grca/planyourvisit/shuttle-buses.htm" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/30 px-6 py-3 text-sm font-black uppercase">Проверить shuttle</a></div></div></section>
<section className="border-b border-teal-100 bg-teal-50/60 px-6 py-10"><div className="mx-auto grid max-w-6xl gap-4 md:grid-cols-4">{[[Users,'Темп','Самый медленный участник'],[Bus,'Транспорт','Бесплатный shuttle'],[Utensils,'Перерыв','Еда до общей усталости'],[BedDouble,'База','Village или Tusayan']].map(([Icon,label,value]:any)=><article key={label} className="rounded-xl border border-teal-100 bg-white p-4"><Icon className="mb-3 h-5 w-5 text-teal-700"/><p className="text-[10px] font-black uppercase tracking-[.2em] text-zinc-400">{label}</p><p className="mt-2 text-sm font-black">{value}</p></article>)}</div></section>
<section className="px-6 py-14"><div className="mx-auto max-w-6xl"><p className="text-[10px] font-black uppercase tracking-[.25em] text-teal-700">Выберите ритм</p><h2 className="mt-3 text-3xl font-black uppercase md:text-4xl">Три реалистичных плана</h2><div className="mt-8 grid gap-4 lg:grid-cols-3">{plans.map(p=><article key={p.title} className="rounded-xl border border-zinc-100 p-5 shadow-sm"><h3 className="text-xl font-black">{p.title}</h3><p className="mt-3 rounded-lg bg-teal-50 p-3 text-xs font-black uppercase text-teal-800">{p.for}</p><p className="mt-4 text-sm leading-7 text-zinc-600">{p.text}</p></article>)}</div></div></section>
<section className="border-y border-teal-100 bg-teal-50/60 px-6 py-14"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black uppercase md:text-4xl">Четыре полезные точки</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{stops.map(s=>{const Icon=s.icon;return <article key={s.title} className="rounded-xl border border-teal-100 bg-white p-5"><Icon className="mb-4 h-6 w-6 text-teal-700"/><h3 className="text-xl font-black">{s.title}</h3><p className="mt-3 text-sm leading-7 text-zinc-600">{s.text}</p></article>})}</div></div></section>
<section className="px-6 py-14"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><ShieldCheck className="h-8 w-8 text-teal-700"/><h2 className="mt-4 text-3xl font-black uppercase">Безопасность до фотографии</h2><p className="mt-4 leading-7 text-zinc-600">Край, высота, жара, снег и молнии важнее списка достопримечательностей.</p></div><div className="grid gap-3">{safety.map(x=><div key={x} className="flex gap-3 rounded-xl border border-zinc-100 p-4"><ShieldCheck className="mt-1 h-5 w-5 flex-none text-teal-700"/><p className="text-sm leading-7">{x}</p></div>)}</div></div></section>
<section className="bg-slate-950 px-6 py-14 text-white"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-black uppercase">Дальше: полный русский гид</h2><p className="mt-4 leading-7 text-zinc-300">Еда, жильё, сезонные решения, маршрут на день и официальные ссылки собраны в Health & Travels.</p><a href="https://healthandtravels.com/ru/grand-kanon-s-detmi?utm_source=sage&utm_medium=cta&utm_campaign=grand_canyon_ru" className="mt-6 inline-block rounded-full bg-teal-100 px-6 py-3 text-sm font-black uppercase text-teal-950">Читать полный гид</a></div><div><h2 className="text-3xl font-black uppercase">Поделиться планом</h2><SharePlanPanel title="Отправьте семье" description="Отправьте короткий план группе и заранее согласуйте темп поездки." quickPlanText={shareText} voteText={shareText} eventContext="russian_grand_canyon_with_kids" locale="ru" /></div></div></section>
<section className="px-6 py-14"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-black uppercase">Частые вопросы</h2><div className="mt-6 space-y-4">{faqs.map(f=><details key={f.question} className="rounded-xl border border-zinc-100 p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-sm leading-7 text-zinc-600">{f.answer}</p></details>)}</div></div></section>
</main>}
