import React, { useMemo, useState } from 'react';
import { ExternalLink, MapPin, PhoneCall, Search, Share2, ShoppingBasket } from 'lucide-react';
import { Link } from 'react-router-dom';
import SEOJsonLd from '../components/SEOJsonLd';
import { trackEvent } from '../utils/analytics';

const spanishUrl = 'https://sage.healthandtravels.com/es/arizona/buscador-comida-necesidades-dieteticas';
const englishUrl = 'https://sage.healthandtravels.com/arizona/food-stop-finder';
const destinations = ['Phoenix', 'Scottsdale', 'Tucson', 'Sedona', 'Flagstaff', 'Payson', 'Prescott', 'Yuma', 'Lake Havasu City', 'Show Low', 'Pinetop-Lakeside', 'Bisbee', 'Williams', 'Cottonwood', 'Jerome', 'Page', 'Grand Canyon Village', 'Oro Valley'];
const needs = ['Vegetariano', 'Vegano', 'Sin gluten', 'Sin lácteos', 'Alergia a frutos secos', 'Alergia al huevo', 'Halal', 'Kosher'];
const meals = ['Comida en restaurante', 'Parada rápida', 'Desayuno', 'Supermercado o picnic'];
const mapsUrl = (query: string) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
function setAlternate(hreflang: string, href: string) { let link = document.querySelector<HTMLLinkElement>(`link[rel="alternate"][hreflang="${hreflang}"]`); if (!link) { link = document.createElement('link'); link.rel = 'alternate'; link.hreflang = hreflang; document.head.appendChild(link); } link.href = href; }

export default function SpanishArizonaFoodStopFinder() {
  const params = new URLSearchParams(window.location.search);
  const [location, setLocation] = useState(params.get('location') || '');
  const [selectedNeeds, setSelectedNeeds] = useState<string[]>(params.get('needs')?.split(',').filter((need) => needs.includes(need)) || []);
  const [meal, setMeal] = useState(params.get('meal') || meals[0]);
  const [showResults, setShowResults] = useState(Boolean(params.get('location')));
  const [copied, setCopied] = useState('');
  React.useEffect(() => { const previous = document.documentElement.lang; document.documentElement.lang = 'es'; setAlternate('es', spanishUrl); setAlternate('en', englishUrl); setAlternate('x-default', englishUrl); return () => { document.documentElement.lang = previous || 'en'; }; }, []);
  const needText = selectedNeeds.length ? selectedNeeds.join(' y ') : 'para familias';
  const restaurantQuery = `${meal.toLowerCase()} ${needText} en ${location || 'Arizona'}`;
  const groceryQuery = `supermercado con opciones ${needText} en ${location || 'Arizona'}`;
  const callScript = useMemo(() => `Hola, estamos viajando y necesitamos opciones ${selectedNeeds.length ? selectedNeeds.join(', ') : 'para las necesidades dietéticas de nuestra familia'}. Antes de ir, ¿podrían decirme qué platos podrían servirnos, si usan freidoras o parrillas compartidas y qué hacen para reducir el contacto cruzado?`, [selectedNeeds]);
  const updateNeed = (need: string) => setSelectedNeeds((current) => current.includes(need) ? current.filter((item) => item !== need) : [...current, need]);
  const buildPlan = (event: React.FormEvent) => { event.preventDefault(); setShowResults(true); const next = new URL(window.location.href); next.searchParams.set('location', location.trim()); next.searchParams.set('meal', meal); selectedNeeds.length ? next.searchParams.set('needs', selectedNeeds.join(',')) : next.searchParams.delete('needs'); window.history.replaceState({}, '', next); trackEvent('food_stop_finder_submit', { location: location.trim(), dietary_needs: selectedNeeds.join('|') || 'none', meal_type: meal, language: 'es' }); };
  const copy = async (text: string, label: string) => { await navigator.clipboard.writeText(text); setCopied(label); window.setTimeout(() => setCopied(''), 1800); };
  return <>
    <SEOJsonLd title="Buscador de comida familiar en Arizona | Sage" description="Busca restaurantes y supermercados en Arizona según las necesidades dietéticas de tu familia y prepara las preguntas que debes hacer antes de comer." url={spanishUrl} faqs={[{question:'¿Una etiqueta dietética garantiza que un restaurante sea seguro para alergias?',answer:'No. Confirma directamente los ingredientes, la preparación, el equipo compartido y el contacto cruzado.'},{question:'¿Qué debe preguntar una familia antes de elegir dónde comer?',answer:'Pregunta por ingredientes actuales, sustituciones, freidoras o parrillas compartidas, espacio de preparación y la capacidad real de atender la necesidad específica.'}]} />
    <div className="bg-amber-50/60">
      <header className="mx-auto max-w-5xl px-6 pb-10 pt-14 text-center md:pt-20"><div className="mb-5 flex justify-center gap-2 text-xs font-black uppercase"><Link to="/arizona/food-stop-finder" className="rounded-full border border-zinc-300 bg-white px-4 py-2">English</Link><span className="rounded-full bg-emerald-700 px-4 py-2 text-white">Español</span></div><p className="text-xs font-black uppercase tracking-[0.28em] text-emerald-700">Herramienta para viajar en familia</p><h1 className="mt-4 text-4xl font-black tracking-tight text-zinc-950 md:text-6xl">Encuentra una parada para comer que funcione para tu familia.</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-zinc-600">Crea búsquedas actuales y usa un guion sencillo para confirmar lo importante antes de que todos tengan hambre.</p></header>
      <main className="mx-auto max-w-5xl px-6 pb-20"><form onSubmit={buildPlan} className="rounded-3xl border border-amber-200 bg-white p-6 shadow-sm md:p-9">
        <label htmlFor="food-location-es" className="block text-sm font-black uppercase tracking-wider text-zinc-800">¿En qué lugar de Arizona?</label><input id="food-location-es" list="arizona-food-destinations-es" required value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Prueba Sedona, Tucson o Flagstaff" className="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3 text-base outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100"/><datalist id="arizona-food-destinations-es">{destinations.map((destination) => <option key={destination} value={destination}/>)}</datalist>
        <fieldset className="mt-7"><legend className="text-sm font-black uppercase tracking-wider text-zinc-800">Necesidades dietéticas</legend><div className="mt-3 grid gap-2 sm:grid-cols-2 md:grid-cols-4">{needs.map((need) => <label key={need} className={`cursor-pointer rounded-xl border px-4 py-3 text-sm font-bold ${selectedNeeds.includes(need) ? 'border-emerald-600 bg-emerald-50 text-emerald-900' : 'border-zinc-200 text-zinc-700'}`}><input type="checkbox" checked={selectedNeeds.includes(need)} onChange={() => updateNeed(need)} className="mr-2 accent-emerald-700"/>{need}</label>)}</div></fieldset>
        <fieldset className="mt-7"><legend className="text-sm font-black uppercase tracking-wider text-zinc-800">¿Qué tipo de parada?</legend><div className="mt-3 flex flex-wrap gap-2">{meals.map((option) => <label key={option} className={`cursor-pointer rounded-full border px-4 py-2 text-sm font-bold ${meal === option ? 'border-blue-700 bg-blue-50 text-blue-900' : 'border-zinc-200 text-zinc-700'}`}><input type="radio" name="meal-es" value={option} checked={meal === option} onChange={() => setMeal(option)} className="sr-only"/>{option}</label>)}</div></fieldset>
        <button type="submit" className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-6 py-4 text-sm font-black uppercase tracking-wider text-white hover:bg-emerald-800 sm:w-auto"><Search className="h-5 w-5"/>Crear mi plan de comida</button>
      </form>
      {showResults && location.trim() && <section aria-live="polite" className="mt-8 space-y-5"><div className="grid gap-4 md:grid-cols-2"><a href={mapsUrl(restaurantQuery)} target="_blank" rel="noopener noreferrer" onClick={() => trackEvent('food_stop_maps_click',{search_type:'restaurant',location,language:'es'})} className="rounded-2xl bg-blue-900 p-6 text-white hover:bg-blue-950"><MapPin className="h-7 w-7"/><h2 className="mt-4 text-xl font-black">Buscar restaurantes</h2><p className="mt-2 text-sm leading-6 text-blue-100">Abre una búsqueda en Google Maps para {restaurantQuery}.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold">Ver resultados actuales <ExternalLink className="h-4 w-4"/></span></a><a href={mapsUrl(groceryQuery)} target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-zinc-200 bg-white p-6"><ShoppingBasket className="h-7 w-7 text-emerald-700"/><h2 className="mt-4 text-xl font-black">Buscar comida de respaldo</h2><p className="mt-2 text-sm leading-6 text-zinc-600">Un picnic o alimentos conocidos pueden salvar el día si un restaurante no puede confirmar tus necesidades.</p></a></div>
        <div className="rounded-2xl border border-amber-300 bg-amber-50 p-6"><div className="flex items-center gap-3"><PhoneCall className="h-6 w-6 text-amber-800"/><h2 className="text-xl font-black">Llama antes de depender del lugar</h2></div><p className="mt-4 rounded-xl bg-white p-4 text-sm leading-7 text-zinc-700">“{callScript}”</p><button type="button" onClick={() => copy(callScript,'script')} className="mt-3 text-sm font-black text-amber-900 underline">{copied === 'script' ? '¡Copiado!' : 'Copiar el guion'}</button><ul className="mt-5 grid gap-2 text-sm leading-6 text-zinc-700 md:grid-cols-2"><li>• Confirma los ingredientes actuales.</li><li>• Pregunta por equipo y utensilios compartidos.</li><li>• Confirma las sustituciones disponibles.</li><li>• Guarda un plan de comida de respaldo.</li></ul></div>
        <div className="rounded-2xl border border-red-200 bg-white p-6 text-sm leading-6 text-zinc-700"><strong>Importante:</strong> Los resultados, reseñas y etiquetas del menú no demuestran que una cocina sea segura para alergias. Para una alergia grave, confirma todo directamente, lleva los medicamentos recetados y comida segura de respaldo, y no comas allí si no puedes verificarlo.</div>
        <div className="flex flex-wrap gap-3"><button type="button" onClick={() => copy(window.location.href,'link')} className="inline-flex items-center gap-2 rounded-xl border border-zinc-300 bg-white px-5 py-3 text-sm font-black"><Share2 className="h-4 w-4"/>{copied === 'link' ? '¡Enlace copiado!' : 'Copiar este plan'}</button><a href={`https://healthandtravels.com/es/paradas-comida-arizona-necesidades-dieteticas.html?location=${encodeURIComponent(location)}&needs=${encodeURIComponent(selectedNeeds.join(','))}&meal=${encodeURIComponent(meal)}&utm_source=sage&utm_medium=planner&utm_campaign=arizona_food_stops_es`} className="px-5 py-3 text-sm font-black text-blue-900 underline">Leer la guía familiar</a></div>
      </section>}</main>
    </div>
  </>;
}
