import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Clock, Compass, Footprints, MapPin, ShieldCheck, Users } from 'lucide-react';
import SEOJsonLd from '../components/SEOJsonLd';
import SharePlanPanel from '../components/SharePlanPanel';

const spanishUrl = 'https://sage.healthandtravels.com/es/arizona/tonto-natural-bridge-con-ninos';
const englishUrl = 'https://sage.healthandtravels.com/arizona/tonto-natural-bridge-with-kids';
const faqs = [
  { question: '¿Tonto Natural Bridge es apropiado para niños?', answer: 'Sí, cuando el plan se adapta a la capacidad de cada niño. Los miradores, el picnic y el lodge permiten una visita completa aunque los senderos empinados no sean apropiados.' },
  { question: '¿Cuánto tiempo necesita una familia?', answer: 'Medio día sin prisa suele permitir miradores, lodge, picnic y un solo sendero cuidadosamente elegido.' },
  { question: '¿Se permiten perros en los senderos?', answer: 'No. Arizona State Parks indica que los perros no están permitidos en los senderos.' },
];
const versions = [
  { title: 'Miradores y picnic', best: 'Niños pequeños o movilidad mixta', text: 'Disfruten las vistas, el lodge y las áreas verdes sin bajar al cañón.', to: '/trip-builder?plan=ready&location=tonto-natural-bridge&kids=yes&group=family&activity=scenic&length=half-day&season=fall&ages=mixed&shade=true&bathrooms=true&stroller=true&drive=120&language=es' },
  { title: 'Un sendero familiar', best: 'Niños escolares con pisada firme', text: 'Empiecen arriba, evalúen las condiciones y elijan un solo sendero abierto para la persona más lenta.', to: '/trip-builder?plan=ready&location=tonto-natural-bridge&kids=yes&group=family&activity=hike&length=half-day&season=fall&ages=older-kids&shade=true&bathrooms=true&stroller=false&drive=120&language=es' },
  { title: 'Fin de semana en Rim Country', best: 'Familias que quieren ir sin prisa', text: 'Combinen el puente con una noche en Payson y una parada más ligera al día siguiente.', to: '/trip-builder?plan=ready&location=payson&kids=yes&group=family&activity=explore&length=weekend&season=fall&ages=mixed&shade=true&bathrooms=true&stroller=false&drive=180&language=es' },
];
const rules = ['Tratar todos los senderos como empinados y exigentes.','Confirmar senderos, clima, horarios y tarifas el mismo día.','Mantener a los niños cerca de escaleras, desniveles, arroyo y roca mojada.','Salir del cauce cuando amenacen tormentas.','Dejar que la persona más lenta decida el ritmo y el regreso.','Recordar que los perros no están permitidos en los senderos.'];
const planText = ['Plan familiar para Tonto Natural Bridge:','','Empiecen con los miradores y el lodge. Evalúen clima, pisada y energía. Elijan como máximo un sendero abierto y terminen con picnic o comida en Payson.','','Regla: los miradores ya cuentan como éxito; bajar es opcional.','Planificador: https://sage.healthandtravels.com/es/arizona/tonto-natural-bridge-con-ninos'].join('\n');
const voteText = ['¿Qué plan elegimos?','','1. Miradores, lodge y picnic','2. Miradores y un sendero adecuado','3. Una noche en Rim Country','','Planificador: https://sage.healthandtravels.com/es/arizona/tonto-natural-bridge-con-ninos'].join('\n');

function setAlternateLink(hreflang:string,href:string){let link=document.querySelector<HTMLLinkElement>(`link[rel="alternate"][hreflang="${hreflang}"]`);if(!link){link=document.createElement('link');link.rel='alternate';link.hreflang=hreflang;document.head.appendChild(link)}link.href=href}

export default function SpanishTontoNaturalBridgeWithKids() {
  React.useEffect(()=>{const previous=document.documentElement.lang;document.documentElement.lang='es';setAlternateLink('es',spanishUrl);setAlternateLink('en',englishUrl);setAlternateLink('x-default',englishUrl);return()=>{document.documentElement.lang=previous||'en'}},[]);
  return <main className="min-h-screen bg-white text-zinc-950">
    <SEOJsonLd title="Tonto Natural Bridge con niños | Plan familiar | Sage" description="Planea Tonto Natural Bridge con niños: miradores, senderos empinados, clima, movilidad, picnic y tres versiones familiares del día." url={spanishUrl} faqs={faqs} breadcrumbs={[{name:'Sage',url:'https://sage.healthandtravels.com/'},{name:'Arizona en español',url:'https://sage.healthandtravels.com/es/arizona'},{name:'Tonto Natural Bridge con niños',url:spanishUrl}]} />
    <section className="bg-emerald-950 px-6 py-16 text-white md:py-24"><div className="mx-auto max-w-6xl">
      <div className="mb-6 flex gap-3 text-[11px] font-black uppercase tracking-[0.22em]"><Link to="/arizona/tonto-natural-bridge-with-kids" className="rounded-full border border-white/30 px-4 py-2 text-white/80 hover:bg-white hover:text-emerald-950">English</Link><span className="rounded-full bg-emerald-200 px-4 py-2 text-emerald-950">Español</span></div>
      <p className="mb-4 text-[11px] font-black uppercase tracking-[0.3em] text-emerald-300">Plan familiar en Rim Country</p><h1 className="max-w-4xl text-4xl font-black uppercase tracking-tight md:text-6xl">Tonto Natural Bridge con niños</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-emerald-50/80 md:text-xl">Los miradores ya son una aventura completa. Bajen solo cuando el sendero, el clima, la pisada y la energía familiar digan que sí.</p>
      <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to={versions[0].to} className="inline-flex items-center justify-center gap-2 rounded-full bg-emerald-300 px-6 py-4 text-sm font-black uppercase tracking-widest text-emerald-950"><Compass className="h-4 w-4"/> Crear mi plan</Link><a href="https://healthandtravels.com/es/tonto-natural-bridge-con-ninos?utm_source=sage&amp;utm_medium=planner&amp;utm_campaign=tonto_bridge_es" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/30 px-6 py-4 text-sm font-black uppercase tracking-widest">Leer la guía completa <ArrowRight className="h-4 w-4"/></a></div>
    </div></section>
    <section className="px-6 py-14"><div className="mx-auto grid max-w-6xl gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Clock,'Duración','Medio día'],[Footprints,'Regla','Un sendero o ninguno'],[Users,'Ideal','Grupos según capacidad'],[ShieldCheck,'Éxito seguro','Miradores y lodge']].map(([Icon,label,value])=>{const StatIcon=Icon as React.ComponentType<{className?:string}>;return <div key={label as string} className="rounded-2xl border border-zinc-200 p-5"><StatIcon className="h-5 w-5 text-emerald-700"/><p className="mt-4 text-[10px] font-black uppercase tracking-widest text-zinc-400">{label as string}</p><p className="mt-1 font-black">{value as string}</p></div>})}</div></section>
    <section className="bg-zinc-50 px-6 py-16"><div className="mx-auto max-w-6xl"><p className="text-[10px] font-black uppercase tracking-[0.25em] text-emerald-700">Elige tu versión</p><h2 className="mt-3 text-3xl font-black uppercase tracking-tight md:text-4xl">Un plan para la familia real</h2><div className="mt-8 grid gap-6 lg:grid-cols-3">{versions.map(v=><article key={v.title} className="flex flex-col rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black">{v.title}</h3><p className="mt-2 text-xs font-black uppercase tracking-widest text-emerald-700">Ideal para: {v.best}</p><p className="mt-4 flex-1 leading-7 text-zinc-600">{v.text}</p><Link to={v.to} className="mt-6 inline-flex items-center gap-2 font-black text-emerald-800">Usar este plan <ArrowRight className="h-4 w-4"/></Link></article>)}</div></div></section>
    <section className="px-6 py-16"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_0.8fr]"><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-emerald-700">La regla principal</p><h2 className="mt-3 text-3xl font-black uppercase tracking-tight">Los miradores cuentan como éxito</h2><p className="mt-5 leading-8 text-zinc-600">Los senderos son cortos en distancia, pero Arizona State Parks los describe como empinados y exigentes. Pregunten qué está abierto y permitan que la persona más lenta decida si el grupo baja.</p><div className="mt-8 rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h3 className="text-lg font-black">Una vuelta sin culpa</h3><p className="mt-3 leading-7 text-zinc-700">Regresen por miedo, cansancio, roca resbalosa, tormenta, cierre o pérdida de confianza. Las vistas y un picnic completan el día.</p></div></div><aside className="rounded-2xl bg-zinc-950 p-7 text-white"><h2 className="text-2xl font-black">Seis reglas</h2><ul className="mt-5 space-y-4">{rules.map(rule=><li key={rule} className="flex gap-3 text-sm leading-6 text-zinc-300"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-300"/>{rule}</li>)}</ul></aside></div></section>
    <section className="bg-emerald-950 px-6 py-16 text-white"><div className="mx-auto max-w-4xl text-center"><MapPin className="mx-auto h-8 w-8 text-emerald-300"/><h2 className="mt-4 text-3xl font-black uppercase tracking-tight">Consulta los datos actuales</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-emerald-50/75">La guía completa incluye horarios y tarifas verificados, enlaces oficiales, seguridad y preguntas frecuentes.</p><a href="https://healthandtravels.com/es/tonto-natural-bridge-con-ninos?utm_source=sage&amp;utm_medium=planner&amp;utm_campaign=tonto_bridge_es" className="mt-7 inline-flex items-center gap-2 rounded-full bg-emerald-300 px-6 py-4 text-sm font-black uppercase tracking-widest text-emerald-950">Abrir la guía <ArrowRight className="h-4 w-4"/></a></div></section>
    <section className="px-6 py-16"><div className="mx-auto max-w-5xl"><SharePlanPanel title="Compartir el plan de Tonto Natural Bridge" description="Copia el itinerario, manda tres opciones o comparte el planificador." quickPlanText={planText} voteText={voteText} eventContext="tonto_natural_bridge_es"/></div></section>
    <section className="bg-zinc-50 px-6 py-16"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-black uppercase tracking-tight">Preguntas frecuentes</h2><div className="mt-8 space-y-5">{faqs.map(f=><article key={f.question} className="rounded-2xl border border-zinc-200 bg-white p-6"><h3 className="font-black">{f.question}</h3><p className="mt-3 leading-7 text-zinc-600">{f.answer}</p></article>)}</div></div></section>
  </main>;
}
