import React from 'react';
import { Link } from 'react-router-dom';
import { Bus, Compass, MapPin, ShieldCheck, Users, Utensils, BedDouble, Sunrise } from 'lucide-react';
import SEOJsonLd from '../components/SEOJsonLd';
import SharePlanPanel from '../components/SharePlanPanel';
const url='https://sage.healthandtravels.com/es/arizona/gran-canon-con-ninos';
const ru='https://sage.healthandtravels.com/ru/arizona/grand-canyon-with-kids';
const en='https://sage.healthandtravels.com/arizona/grand-canyon';
const faqs=[
{question:'¿El South Rim funciona bien con niños?',answer:'Sí. Mather Point, un tramo apropiado del Rim Trail, Yavapai Geology Museum y descansos frecuentes forman un buen primer día.'},
{question:'¿Tenemos que descender al cañón?',answer:'No. Las vistas desde el borde ofrecen una experiencia completa. Bajar es opcional y el ascenso siempre es más difícil.'},
{question:'¿El shuttle es gratis?',answer:'Sí. Las rutas y horarios cambian según la temporada; revisa el sitio oficial del NPS el mismo día.'},
{question:'¿Dónde conviene dormir?',answer:'Grand Canyon Village reduce traslados; Tusayan está junto a la entrada sur; Williams y Flagstaff funcionan para viajes más largos.'}
];
const plans=[
{title:'Primera visita tranquila',for:'Niños pequeños o adultos mayores',text:'Visitor Center → Mather Point → comida temprana → Junior Ranger. Solo una parada adicional si todos tienen energía.'},
{title:'Caminata junto al borde',for:'Niños de edad escolar',text:'Mather Point → tramo apropiado del Rim Trail → Yavapai Geology Museum → shuttle de regreso.'},
{title:'Grandes vistas, poca conducción',for:'Familias de edades mixtas',text:'Estaciona una vez, usa el shuttle y decide cada parada según la persona con menos energía.'}
];
const stops=[
{title:'Mather Point',icon:Sunrise,text:'La primera gran vista cerca del Visitor Center. Llega temprano para reducir multitudes y estrés.'},
{title:'Yavapai Point',icon:MapPin,text:'Panorama y museo de geología: una buena combinación de exterior e interior.'},
{title:'Rim Trail',icon:Compass,text:'Escoge un tramo desarrollado y da la vuelta antes del cansancio. No todo el sendero tiene barreras.'},
{title:'Shuttle del parque',icon:Bus,text:'Transporte gratuito entre zonas principales, con rutas y horarios estacionales.'}
];
const safety=['Un adulto siempre se coloca entre el niño pequeño y el borde.','No camines hacia atrás para tomar una foto ni corras cerca del precipicio.','Revisa clima, carreteras, rayos, nieve y alertas antes de salir.','En verano evita caminatas exigentes bajo el borde entre 10 a. m. y 4 p. m.','Lleva agua, bocadillos, protección solar y una capa adicional.'];
const share=['Gran Cañón con niños — plan sencillo:','1. Llegar temprano al Visitor Center','2. Mather Point','3. Rim Trail corto hasta Yavapai','4. Comida y Junior Ranger','5. Una parada en shuttle o descanso','','Regla: una vista, una caminata, una pausa.',url].join('\n');
function alt(lang:string,href:string){let l=document.querySelector<HTMLLinkElement>(`link[rel="alternate"][hreflang="${lang}"]`);if(!l){l=document.createElement('link');l.rel='alternate';l.hreflang=lang;document.head.appendChild(l)}l.href=href}
export default function SpanishGrandCanyonWithKids(){React.useEffect(()=>{const old=document.documentElement.lang;document.documentElement.lang='es';alt('es',url);alt('ru',ru);alt('en',en);alt('x-default',en);return()=>{document.documentElement.lang=old||'en'}},[]);
return <main className="min-h-screen bg-white text-zinc-950">
<SEOJsonLd title="Gran Cañón con niños | Plan familiar del South Rim | Sage" description="Guía en español del South Rim con niños: miradores, Rim Trail, shuttle, comida, alojamiento, seguridad y un itinerario familiar." url={url} faqs={faqs} breadcrumbs={[{name:'Sage',url:'https://sage.healthandtravels.com/'},{name:'Arizona en español',url:'https://sage.healthandtravels.com/es/arizona'},{name:'Gran Cañón con niños',url}]} />
<section className="bg-slate-950 px-6 py-20 text-white"><div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-wrap gap-3 text-[11px] font-black uppercase tracking-[.2em]"><Link to="/arizona/grand-canyon" className="rounded-full border border-white/30 px-4 py-2">English</Link><Link to="/ru/arizona/grand-canyon-with-kids" className="rounded-full border border-white/30 px-4 py-2">Русский</Link><span className="rounded-full bg-teal-100 px-4 py-2 text-teal-950">Español</span></div><p className="text-[11px] font-black uppercase tracking-[.3em] text-teal-200">Gran vista · día familiar sencillo</p><h1 className="mt-4 max-w-4xl text-4xl font-black uppercase tracking-tight md:text-6xl">Gran Cañón con niños</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-200">Elige una caminata, usa el shuttle y guarda energía para volver con seguridad, sin intentar ver todo el cañón en un solo día.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/trip-builder?plan=ready&location=grand-canyon&kids=yes&group=family&activity=views&length=full-day&language=es" className="rounded-full bg-blue-700 px-6 py-3 text-sm font-black uppercase">Crear mi plan</Link><a href="https://www.nps.gov/grca/planyourvisit/shuttle-buses.htm" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/30 px-6 py-3 text-sm font-black uppercase">Revisar shuttle</a></div></div></section>
<section className="border-b border-teal-100 bg-teal-50/60 px-6 py-10"><div className="mx-auto grid max-w-6xl gap-4 md:grid-cols-4">{[[Users,'Ritmo','La persona más lenta'],[Bus,'Transporte','Shuttle gratuito'],[Utensils,'Pausa','Comer antes del cansancio'],[BedDouble,'Base','Village o Tusayan']].map(([Icon,label,value]:any)=><article key={label} className="rounded-xl border border-teal-100 bg-white p-4"><Icon className="mb-3 h-5 w-5 text-teal-700"/><p className="text-[10px] font-black uppercase tracking-[.2em] text-zinc-400">{label}</p><p className="mt-2 text-sm font-black">{value}</p></article>)}</div></section>
<section className="px-6 py-14"><div className="mx-auto max-w-6xl"><p className="text-[10px] font-black uppercase tracking-[.25em] text-teal-700">Elige tu ritmo</p><h2 className="mt-3 text-3xl font-black uppercase md:text-4xl">Tres planes realistas</h2><div className="mt-8 grid gap-4 lg:grid-cols-3">{plans.map(p=><article key={p.title} className="rounded-xl border border-zinc-100 p-5 shadow-sm"><h3 className="text-xl font-black">{p.title}</h3><p className="mt-3 rounded-lg bg-teal-50 p-3 text-xs font-black uppercase text-teal-800">{p.for}</p><p className="mt-4 text-sm leading-7 text-zinc-600">{p.text}</p></article>)}</div></div></section>
<section className="border-y border-teal-100 bg-teal-50/60 px-6 py-14"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black uppercase md:text-4xl">Cuatro puntos útiles</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{stops.map(s=>{const Icon=s.icon;return <article key={s.title} className="rounded-xl border border-teal-100 bg-white p-5"><Icon className="mb-4 h-6 w-6 text-teal-700"/><h3 className="text-xl font-black">{s.title}</h3><p className="mt-3 text-sm leading-7 text-zinc-600">{s.text}</p></article>})}</div></div></section>
<section className="px-6 py-14"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><ShieldCheck className="h-8 w-8 text-teal-700"/><h2 className="mt-4 text-3xl font-black uppercase">Seguridad antes que la foto</h2><p className="mt-4 leading-7 text-zinc-600">El borde, la altura, el calor, la nieve y los rayos importan más que completar una lista.</p></div><div className="grid gap-3">{safety.map(x=><div key={x} className="flex gap-3 rounded-xl border border-zinc-100 p-4"><ShieldCheck className="mt-1 h-5 w-5 flex-none text-teal-700"/><p className="text-sm leading-7">{x}</p></div>)}</div></div></section>
<section className="bg-slate-950 px-6 py-14 text-white"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-black uppercase">Lee la guía completa</h2><p className="mt-4 leading-7 text-zinc-300">Comida, alojamiento, decisiones por temporada, itinerario y fuentes oficiales en Health & Travels.</p><a href="https://healthandtravels.com/es/gran-canon-con-ninos?utm_source=sage&utm_medium=cta&utm_campaign=grand_canyon_es" className="mt-6 inline-block rounded-full bg-teal-100 px-6 py-3 text-sm font-black uppercase text-teal-950">Abrir la guía</a></div><div><h2 className="text-3xl font-black uppercase">Compartir el plan</h2><SharePlanPanel title="Envíalo a tu familia" text={share}/></div></div></section>
<section className="px-6 py-14"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-black uppercase">Preguntas frecuentes</h2><div className="mt-6 space-y-4">{faqs.map(f=><details key={f.question} className="rounded-xl border border-zinc-100 p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-sm leading-7 text-zinc-600">{f.answer}</p></details>)}</div></div></section>
</main>}